#서버 포트 설정
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  port: 9090
  file:
    book:
      path: /Users/chuyudam/files/upload/book/
    usedbook:
      path: /Users/chuyudam/files/upload/usedbook/


spring:
  main:
    allow-bean-definition-overriding: true
  jwt:
    secretKey : vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
#Database 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/online_bookstore?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "0408"
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 20
      idle-timeout: 10000
      data-source-properties:
        cachePrepStmts : true #캐쉬 설정 on 
        prepStmtCacheSize : 250 #문서 할당 수
        prepStmtCacheSqlLimit: 2048 #sql 최대길이 byte 단위
        useServerPrepStmts: true # 최신기능 지원설정 on 
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
        use_sql_comments: false
        cache:
          use_sql_comments: false
          use_query_cache: false



  #코드 수정 시 자동으로 컴파일 & 적용
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
    restart:
      enabled: true

#로그 설정
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO
      thymeleaf: OFF
      hibernate:
        SQL : debug
        type:
          descriptor:
            sql : trace
  config : classpath:logback.xml